version: "3.4"

services:
  redis-node1:
    build:
      context: redis
    ports:
      - "7000:7000"
      - "17000:17000"
    restart: always
    volumes:
      - redis-data-node1:/data
    entrypoint:
      [
        redis-server,
        /etc/redis/rediscluster.conf,
        --port,
        "7000",
        --cluster-announce-ip,
        "${ip}",
      ]
  redis-node2:
    build:
      context: redis
    ports:
      - "7001:7001"
      - "17001:17001"
    restart: always
    volumes:
      - redis-data-node2:/data
    entrypoint:
      [
        redis-server,
        /etc/redis/rediscluster.conf,
        --port,
        "7001",
        --cluster-announce-ip,
        "${ip}",
      ]
  redis-node3:
    build:
      context: redis
    ports:
      - "7002:7002"
      - "17002:17002"
    restart: always
    volumes:
      - redis-data-node3:/data
    entrypoint:
      [
        redis-server,
        /etc/redis/rediscluster.conf,
        --port,
        "7002",
        --cluster-announce-ip,
        "${ip}",
      ]
  redis-node4:
    build:
      context: redis
    ports:
      - "7003:7003"
      - "17003:17003"
    restart: always
    volumes:
      - redis-data-node4:/data
    entrypoint:
      [
        redis-server,
        /etc/redis/rediscluster.conf,
        --port,
        "7003",
        --cluster-announce-ip,
        "${ip}",
      ]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node5:
    build:
      context: redis
    ports:
      - "7004:7004"
      - "17004:17004"
    restart: always
    volumes:
      - redis-data-node5:/data
    entrypoint:
      [
        redis-server,
        /etc/redis/rediscluster.conf,
        --port,
        "7004",
        --cluster-announce-ip,
        "${ip}",
      ]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-node6:
    build:
      context: redis
    ports:
      - "7005:7005"
      - "17005:17005"
    restart: always
    volumes:
      - redis-data-node6:/data
    entrypoint:
      [
        redis-server,
        /etc/redis/rediscluster.conf,
        --port,
        "7005",
        --cluster-announce-ip,
        "${ip}",
      ]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
  redis-cluster-creator:
    image: redis
    entrypoint:
      [
        /bin/sh,
        -c,
        'echo "yes" | redis-cli -a pass.123 --cluster create ${ip}:7000 ${ip}:7001 ${ip}:7002 ${ip}:7003 ${ip}:7004 ${ip}:7005 --cluster-replicas 1',
      ]
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
  redisinsights:
    container_name: redis-webui
    image: redislabs/redisinsight:latest
    volumes:
      - redis-webui-data:/data
    ports:
      - "5540:5540"

volumes:
  redis-webui-data: {}
  redis-data-node1: {}
  redis-data-node2: {}
  redis-data-node3: {}
  redis-data-node4: {}
  redis-data-node5: {}
  redis-data-node6: {}